import { Project } from "types/Project";

export const projectsMock: Array<Project> = [
  {
    dependent_repos_count: 45,
    dependents_count: 0,
    deprecation_reason: null,
    description:
      "MUI is a lightweight HTML/CSS/JS framework that follows Google's Material Design guidelines.",
    forks: 454,
    homepage: "https://www.muicss.com",
    keywords: [
      "material design",
      "frontend framework",
      "html, css, and js framework",
      "email css template",
      "css-framework",
      "google-material",
      "javascript",
      "lightweight-css-framework",
      "material",
      "meteor",
      "mui",
      "nodejs",
    ],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "0.10.2",
    latest_release_published_at: "2020-04-23T09:07:51.000Z",
    latest_stable_release_number: "0.10.2",
    latest_stable_release_published_at: "2020-04-23T09:07:51.000Z",
    license_normalized: false,
    licenses: "MIT",
    name: "mui",
    normalized_licenses: ["MIT"],
    package_manager_url: null,
    platform: "Bower",
    rank: 14,
    repository_license: null,
    repository_url: "https://github.com/muicss/mui.git",
    stars: 4445,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 0,
    dependents_count: 0,
    deprecation_reason: null,
    description:
      "MUI-最接近原生App体验的前端框架\n(由于dcloud未在Nuget上传该包,方便.NETer故提供)",
    forks: 6761,
    homepage: "https://github.com/dcloudio/mui",
    keywords: ["mui", "neverc"],
    language: "JavaScript",
    latest_download_url: "https://www.nuget.org/api/v2/package/mui/1.0.1",
    latest_release_number: "1.0.1",
    latest_release_published_at: "2016-10-27T07:45:14.650Z",
    latest_stable_release_number: "1.0.1",
    latest_stable_release_published_at: "2016-10-27T07:45:14.650Z",
    license_normalized: false,
    licenses: "",
    name: "mui",
    normalized_licenses: ["MIT"],
    package_manager_url: "https://www.nuget.org/packages/mui/",
    platform: "NuGet",
    rank: 13,
    repository_license: "MIT",
    repository_url: "https://github.com/dcloudio/mui",
    stars: 13256,
    status: null,
    versions: [
      {
        number: "1.0.0",
        published_at: "2016-08-11T02:37:56.643Z",
        spdx_expression: "NONE",
        original_license: null,
        researched_at: null,
        repository_sources: ["NuGet"],
      },
      {
        number: "1.0.1",
        published_at: "2016-10-27T07:45:14.650Z",
        spdx_expression: "NONE",
        original_license: null,
        researched_at: null,
        repository_sources: ["NuGet"],
      },
    ],
  },
];
